### ISSUE TITLE
'Encode to Switch' button not doing anything

### ISSUE THREAD

**Issue by All3el3e** [eugeneration/HappyIslandDesigner#1]
It's probably because the game hasn't been released yet, but the the button which uses [ / ] doesn't appear to be doing anything.

Love your work!

**Comment by eugeneration** [comment]
The 'encode to console' button prints out map data to the browser 'console' window (not a video game console). If you press the '/' button and open the browser console (Control+Shift+J in Chrome), you should see a long JSON string. This string represents the map data.

I included this mostly for debugging purposes, but also in case you wanted to save a very complex map that is too big to fit in the image data. In the future I plan on allowing people to save this string as a text file and load it in as a text file, in case they can't use an image.
