### ISSUE TITLE
Add my island ! [South A2]

### ISSUE THREAD

**Issue by S1NB0Y** [eugeneration/HappyIslandDesigner#107]
Here's mine ! Seems to be South A2 from this listing: https://github.com/eugeneration/HappyIslandDesigner/issues/59#issuecomment-629715285

The island I've recreated into Island Designer:
https://imgur.com/sL1nDBc

The image I referenced (from my own savefile):
https://imgur.com/kQ8BTJN

**Comment by eugeneration** [comment]
thank you! Merging into #59
