### ISSUE TITLE
My starting map not there

### ISSUE THREAD

**Issue by archambaultalex** [eugeneration/HappyIslandDesigner#119]
![15986296068297697883629461890829](https://user-images.githubusercontent.com/25965446/91587020-307fd580-e924-11ea-83c0-aa22da5726c2.jpg)

**Comment by EdesRozsa** [comment]
Have downloaded image. Am working on a trace.

**Comment by EdesRozsa** [comment]
![Peachy-RowsA-C](https://user-images.githubusercontent.com/52076181/92986166-d2580400-f486-11ea-9e3c-574b95efba05.png)

WIP

**Comment by EdesRozsa** [comment]
![Peachy-RowsA-D](https://user-images.githubusercontent.com/52076181/92987665-af335180-f492-11ea-9626-3244cada5f32.png)

Believe that some terraforming has been done on the island in the image provided, but am tracing faithfully to the image, due to unfamiliarity with the default status.
