### ISSUE TITLE
Make it easier to get your map from the game into the editor

### ISSUE THREAD

**Issue by eugeneration** [eugeneration/HappyIslandDesigner#13]

**Comment by eugeneration** [comment]
I am working on a feature that will allow uploading a photo from your phone/webcam, fix the perspective, and create an overlay that allows you to trace the island. It probably won't be possible to automatically generate the island from this image.

SerialK is tentatively working on a feature that allows uploading a screenshot from the switch and automatically generating a map from the image.

**Comment by ssteigen** [comment]
Here's a screenshot from my game, if that helps.

![91635652_10157615641208025_7717679244452560896_o](https://user-images.githubusercontent.com/1730676/77940502-c684d680-7286-11ea-90e6-8d7dd1b296f9.jpg)

**Comment by ssteigen** [comment]
Separated the screenshot feature out into a separate ticket. #15

**Comment by eugeneration** [comment]
Completed with #53
