### ISSUE TITLE
Load map does not work

### ISSUE THREAD

**Issue by mathildapurr** [eugeneration/HappyIslandDesigner#14]
After saving an image, if I open a new map and select "load map" using that image, the map will appear as blank.

**Comment by ssteigen** [comment]
Can you post the image here so we can try it?

**Comment by eugeneration** [comment]
http://virtualducttape.com/files/HappyIslandDesigner_1585334401513.png

**Comment by FlynnFarrow** [comment]
Also not working for me, not compressed/modified neither.

![HappyIslandDesigner_1585746214236](https://user-images.githubusercontent.com/56035537/78140502-08964f80-7422-11ea-9e44-3cf45d2c4185.png)

**Comment by FlynnFarrow** [comment]
Don't know if it makes a difference using my repo to create the map then testing it in my repo and this repo but not working in either.

**Comment by eugeneration** [comment]
In #58 I changed the compression to do UTF 16 rather than the default which compresses to an invalid js string. Because it is a valid string, steganography should be able to correctly store the data.
