### ISSUE TITLE
[Feature] Add Browser-update.org Banner

### ISSUE THREAD

**Issue by ssteigen** [eugeneration/HappyIslandDesigner#17]
Notify visitors to update their browser to the latest version. https://browser-update.org

```
<script> 
var $buoop = {required:{e:-1,f:-1,o:-1,s:-1,c:-1},insecure:true,api:2020.03 }; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>
```

**Comment by FlynnFarrow** [comment]
I was going to do that in pull request #11 I think.

**Comment by ssteigen** [comment]
> I was going to do that in pull request #11 I think.

Looks like your PR had some extra stuff in it. I couldn't figure out how to clean it up, so I opened a new PR.

**Comment by FlynnFarrow** [comment]
Yeah I didn't know how to clean it out neither.

**Comment by FlynnFarrow** [comment]
Also it would be cool if you add a button to share to social media or even do mobile apps which I'm trying out now.

**Comment by FlynnFarrow** [comment]
Using my repo, site doesn't load properly on chrome 44 so for the chrome category it needs to be newer than that.

![2020-03-31 15-46-35 Screenshot](https://user-images.githubusercontent.com/56035537/78039966-ae848400-7366-11ea-8790-04836f6943ea.jpg)

**Comment by FlynnFarrow** [comment]
Chrome 55 works so in chrome area, best in between 44-55 for chrome category.

![2020-03-31 15-49-58 Screenshot](https://user-images.githubusercontent.com/56035537/78040115-e8ee2100-7366-11ea-8996-5106aef4a1be.jpg)
