### ISSUE TITLE
[Feature Request] Rotated ramp and Shift for left+right scrolling

### ISSUE THREAD

**Issue by dvdcd** [eugeneration/HappyIslandDesigner#3]
1. The ramps only have the one direction, while the bridges have them rotated. It'd be great to have a rotated ramp that ends on the right side.

2. When you are zoomed in i can't figure out how to move left and right on the map without zooming out and back in again. Using shift+scroll wheel for left and right movement would make using the editor while zoomed in a lot simpler.

Amazing work so far, and thank you for considering my feature ideas.

**Comment by eugeneration** [comment]
1. I plan on adding more sprites soon. Maybe I could offer the ability to rotate/sprites
2. I added new functionality in the v0.1 release. Hold alt + scroll to zoom in. Hold space + drag to pan around. This key mapping is based on Photoshop.

**Comment by eugeneration** [comment]
I added multiple bridges and ramps that are in all 4 directions.
