### ISSUE TITLE
Switching asset tabs is often confusing

### ISSUE THREAD

**Issue by alexthake** [eugeneration/HappyIslandDesigner#47]
I suggest that changing the tab between terrain and path should also update you to the selected tool in that category, as currently you need to reselect the tool that you need in that tab even if it was the last one used. Either this or the selection should clear when you go back to a previous tab after using another tool.

issue example:

Draw some land
switch to path tab
select a path
draw some paths
switch back to terrain tab
terrain of choice already selected
try to draw land
path appears
confusion
click on already visually selected tool to update it
draw land

**Comment by FlynnFarrow** [comment]
I see.

**Comment by eugeneration** [comment]
That's definitely a bug - the UI is updating properly but I guess I never bothered to check that the brush was actually changed! This definitely affects the core experience of the app so I'll add this to the to-fix bug list
