### ISSUE TITLE
Map saving issues

### ISSUE THREAD

**Issue by Jademalo** [eugeneration/HappyIslandDesigner#51]
Not really sure of the cause of this, it happened on both Chrome and Firefox. For some reason, the following images don't load properly and turn the entire island into sand.

Firefox - 
![HappyIslandDesigner_1586130841635](https://user-images.githubusercontent.com/386846/78513567-8cdf2e80-77a4-11ea-9c21-e738882fa01e.png)
Chrome - 
![HappyIslandDesigner_1586132180252](https://user-images.githubusercontent.com/386846/78513574-92d50f80-77a4-11ea-9fed-9ee016caf888.png)
Chrome - 
![HappyIslandDesigner_1586132249824](https://user-images.githubusercontent.com/386846/78513576-94063c80-77a4-11ea-9ca2-c1a79963a4dd.png)

The same face was drawn in both Firefox and Chrome, and doesn't load correctly in either. 

In addition features such as paths and buildings aren't being loaded correctly, though that issue seems separate and is covered by #14

**Comment by eugeneration** [comment]
#56 should fix this!

#55  also included a change that should prevent this kind of map from saving incorrectly.

I don't think I'll be able to fix #14, as it seems like the compressed data got corrupted, but if I get more reports then I will check it out again
