### ISSUE TITLE
Map template  Bottom Left

### ISSUE THREAD

**Issue by YUESAI** [eugeneration/HappyIslandDesigner#54]
`{"version":1,"objects":{"amenities_dock":[104,89]},"drawing":{"sand":[[7,71,6,70,6,68,5,67,5,62,3,60,2,60,1,59,1,53,2,52,2,51,3,50,5,50,5,44,6,43,7,43,8,42,16,42,19,45,25,45,26,46,30,46,35,51,36,51,37,52,44,52,46,50,46,49,48,47,48,46,49,45,50,45,51,44,56,44,57,45,60,45,63,48,64,48,65,49,66,49,67,50,67,54,65,56,65,58,66,59,66,60,71,65,72,65,73,66,73,71,74,72,74,73,69,78,69,81,70,82,70,89,69,90,70,91,68,93,63,93,62,94,60,94,59,95,55,95,54,94,52,94,51,93,47,93,42,88,36,88,36,90,37,91,37,92,36,93,35,93,34,92,27,92,26,91,26,86,25,86,23,88,22,88,17,93,15,93,14,92,13,92,9,88,9,86,7,84,7,83,5,81,5,79,7,77],[33,44,33,43,32,42,27,42,26,41,21,41,20,40,20,39,19,38,8,38,7,37,6,37,5,36,5,31,6,30,6,28,5,27,5,26,4,25,2,25,1,24,1,20,2,19,3,19,4,18,5,18,5,9,6,8,8,8,9,9,9,11,10,11,11,10,15,10,16,11,16,13,17,12,18,12,19,13,20,12,22,12,23,11,24,12,26,12,27,11,29,11,30,10,31,10,32,11,32,13,33,12,34,12,35,13,36,12,37,12,38,11,39,11,40,12,42,12,43,11,45,11,46,10,47,10,48,11,48,12,49,12,49,10,51,8,52,8,53,7,58,7,59,8,59,9,61,9,64,12,66,12,67,13,68,12,69,12,70,11,71,11,72,12,74,12,75,11,77,11,78,10,79,10,80,11,80,12,81,13,82,13,84,11,85,12,86,12,87,11,89,13,91,13,92,12,94,12,95,13,96,13,97,12,97,11,98,10,100,10,101,11,102,11,104,9,106,9,107,10,107,18,105,20,105,25,106,26,106,29,107,30,107,31,108,32,108,33,105,36,105,37,104,38,104,43,106,45,106,46,107,47,107,49,108,50,108,53,107,54,107,56,106,57,106,61,107,62,107,66,106,67,106,69,107,70,108,69,111,72,111,73,109,73,109,75,108,76,107,76,106,77,106,78,107,79,107,82,104,85,104,87,106,89,106,92,104,94,100,94,99,93,95,93,94,92,93,92,91,94,88,94,87,95,84,95,83,94,82,94,81,93,78,93,77,92,77,91,76,90,76,87,74,85,74,81,73,80,76,77,76,76,78,74,78,72,77,71,77,66,75,64,75,63,74,62,73,62,70,59,70,56,71,55,71,50,73,48,74,48,76,46,83,46,87,42,90,42,91,43,92,43,93,42,93,40,94,39,94,36,95,35,95,34,94,33,92,33,91,34,91,37,89,39,84,39,83,40,83,41,82,42,75,42,74,43,73,43,70,46,68,46,67,45,66,45,63,42,62,42,61,41,58,41,57,40,51,40,50,41,48,41,44,45,44,46,42,48,38,48,37,47,36,47],[67,32,68,31,68,30,69,29,70,29,72,31,72,32,73,33,75,33,76,32,76,29,74,27,73,27,72,26,72,19,73,19,74,18,74,17,73,16,64,16,63,17,63,18,64,19,67,19,68,20,68,25,67,26,66,26,63,29,63,31,64,32],[88,76,89,75,89,73,87,73,85,71,84,71,83,72,83,75,84,76],[51,60,51,62,52,63,56,63,57,62,57,59,56,58,55,58,54,59,52,59]],"level1":[[13,44,12,43,12,42,16,42,19,45,25,45,26,46,30,46,35,51,36,51,37,52,44,52,46,50,46,49,48,47,48,46,49,45,50,45,51,44,56,44,57,45,60,45,63,48,64,48,65,49,66,49,67,50,67,54,65,56,65,58,66,59,66,60,71,65,72,65,73,66,73,71,74,72,74,73,69,78,69,81,70,82,70,84,68,84,67,83,63,83,62,84,61,84,60,85,57,85,56,86,52,86,49,83,36,83,35.5,83.5,35,83,15,83,13,81,13,79,12,78,12,76,13,75,13,73,12,72,12,71,11,70,11,67,13,65],[33,44,33,43,32,42,27,42,26,41,21,41,20,40,20,39,19,38,12,38,12,36,13,35,13,30,12,29,12,28,11,27,11,26,9,24,7,24,6,25,2,25,1,24,1,20,2,19,3,19,4,18,6,18,7,19,8,19,9,20,11,20,13,18,13,14,14,13,91,13,92,12,92,13,97,13,99,15,99,17,100,18,100,22,99,23,99,37,100,38,100,40,101,41,101,44,100,45,100,47,99,48,99,50,100,51,100,55,99,56,99,58,100,59,100,62,99,63,99,65,100,66,100,68,99,69,99,72,101,74,101,76,99,78,99,82,98,83,95,83,94,84,93,84,91,86,88,86,87,85,86,85,85,84,83,84,82,83,77,83,76,84,74,84,74,81,73,80,76,77,76,76,78,74,78,72,77,71,77,66,75,64,75,63,74,62,73,62,70,59,70,56,71,55,71,50,73,48,74,48,76,46,83,46,87,42,90,42,91,43,92,43,93,42,93,40,94,39,94,36,95,35,95,34,94,33,92,33,91,34,91,37,89,39,84,39,83,40,83,41,82,42,75,42,74,43,73,43,70,46,68,46,67,45,66,45,63,42,62,42,61,41,58,41,57,40,51,40,50,41,48,41,44,45,44,46,42,48,38,48,37,47,36,47],[67,32,68,31,68,30,69,29,70,29,72,31,72,32,73,33,75,33,76,32,76,29,74,27,73,27,72,26,72,19,73,19,74,18,74,17,73,16,64,16,63,17,63,18,64,19,67,19,68,20,68,25,67,26,66,26,63,29,63,31,64,32],[88,76,89,75,89,73,87,73,85,71,84,71,83,72,83,75,84,76],[51,60,51,62,52,63,56,63,57,62,57,59,56,58,55,58,54,59,52,59]],"level2":[14,25,14,24,13,23,13,16,16,13,91,13,92,12,92,13,96,13,99,16,99,19,98,20,98,21,97,22,97,25,99,27,99,48,96,51,94,51,93,52,87,52,86,51,85,51,84,50,81,50,80,49,80,46,83,46,87,42,90,42,91,43,92,43,93,42,93,40,94,39,94,36,95,35,95,34,94,33,92,33,91,34,91,37,89,39,84,39,83,40,83,41,82,42,80,42,80,27,78,25,76,25,75,24,72,24,72,19,73,19,74,18,74,17,73,16,64,16,63,17,63,18,64,19,67,19,68,20,68,24,64,24,63,25,57,25,55,27,55,28,52,31,52,32,51,33,46,33,45,32,43,32,42,33,39,33,38,32,34,32,33,33,25,33,24,32,22,32,20,30,20,29,19,28,18,28,17,27,16,27],"level3":[[21,24,21,22,20,21,20,20,19,19,19,17,20,16,21,16,23,14,44,14,46,16,46,17,47,18,48,18,49,19,49,21,47,23,46,23,45,24,44,24,42,26,40,26,39,25,37,25,36,26,36,27,35,28,33,28,32,29,26,29,25,28,24,28,23,27,23,26],[97,29,98,30,98,35,97,36,97,39,98,40,98,44,97,45,96,45,94,47,90,47,87,44,87,42,90,42,91,43,92,43,93,42,93,40,94,39,94,36,95,35,95,34,94,33,92,33,91,34,91,37,89,39,88,39,88,32,89,31,89,28,90,27,94,27,96,29],[78,19,77,20,72,20,72,19,73,19,74,18,74,17,73,16,64,16,63,17,63,18,64,19,67,19,68,20,66,20,65,21,63,21,62,20,60,20,58,18,58,15,59,14,81,14,82,15,82,18,81,19],[92,12,92,13,91,13]],"rock":[[5,12,5,9,6,8,8,8,9,9,9,11,10,11,11,10,15,10,16,11,16,13,14,13,13,14,13,15,11,15,10,14,7,14],[33,12,34,12,35,13,36,12,37,12,38,11,39,11,40,12,42,12,43,11,45,11,46,10,47,10,48,11,48,12,49,12,49,10,51,8,52,8,53,9,53,11,58,11,59,10,59,9,61,9,64,12,66,12,67,13,68,12,69,12,70,11,71,11,72,12,74,12,75,11,77,11,78,10,79,10,80,11,80,12,81,13,16,13,17,12,18,12,19,13,20,12,22,12,23,11,24,12,26,12,27,11,29,11,30,10,31,10,32,11,32,13],[82,13,84,11,85,12,86,12,87,11,89,13],[92,12,94,12,95,13,91,13],[97,11,98,10,100,10,101,11,102,11,104,9,106,9,107,10,107,12,105,14,102,14,101,15,99,15,97,13,96,13,97,12],[9,38,8,38,7,37,9,37],[7,43,8,42,9,42,10,43,9,44,8,44],[5,50,6,51,7,51,8,52,8,55,9,56,9,61,7,63,6,63,3,60,2,60,1,59,1,53,2,52,2,51,3,50],[31,85,30,85,29,84,30,83,36,83,37,84,37,85,36,86,35,86,35,87,36,88,36,90,37,91,37,92,36,93,35,93,34,92,27,92,26,91,26,86,25,85,25,83,27,83,27,86,32,86,33,85,32,84],[69,90,70,91,69,92,68,92,68,91],[76,90,76,89,77,89,77,91],[111,72,111,73,109,73,109,75,108,76,107,76,105,74,105,73,104,73,102,71,102,69,103,68,105,68,107,70,108,69],[100,24,100,23,100.5,22.5,100,22,100,20,101,20,102,19,103,20,103,22,101,24]]}}`

**Comment by YUESAI** [comment]
![20200407111422](https://user-images.githubusercontent.com/16502883/78626400-4501f980-78c1-11ea-9fc5-71cc08aa3aea.png)

**Comment by eugeneration** [comment]
Merging into #59
