### ISSUE TITLE
Image Save/Load Issue & Map: West Outlet Bottom Left

### ISSUE THREAD

**Issue by micsa91** [eugeneration/HappyIslandDesigner#57]
Hi there, first of all big thanks for working on this awesome project!
So, I recreated the map I chose in my game, which is the bottom left one shown on here:
https://imgur.com/ltSsS3Q.

I had to do it twice, because the editor could not read my saved image back into the editor.
Thus I tried reading the broken image with this tool:
https://www.peter-eigenschink.at/projects/steganographyjs/showcase/
What it gave me were asian characters instead of something like the console output.
When I recreated it, I took the console output and used the tool to save it into the image manually which works like a charm.

For troubleshooting reasons I'm providing both versions on here, 'map' and 'broken':
https://imgur.com/a/iLXRWK7

<details>
  <summary>'broken' (click me)</summary>
  㞂⁮੠丌ްᶈ׀䘀킀♐ↀ‹骠쾒㦠㚝ʲ満ⲛ뛇Ⰰ즀첽。擀ᎄ昀〃擌셳ᤋ噠Ǎ㱦鵛퇰遨稬饡澺曇퀬냥ꃴ䜇঺㡅댊獺㭸쩛घԙ飄奣ਈ䯰⦥蓅蚋抰�骊넄牱ᖅ៤珪਱옩惊㊋⥫⡋둈䧉怎嗊爉쨻賧쫗쯷䪧䧙뛍䮺槚ࡨ螉箉餏ﮊ먙�㤎例䶊춋ᠦ볨ᣋ䖅柨㵩葱ᤏ鞂ೠ숳鐡᰼ⴿ଩闡ꔊㅈꉇᇃ衉堄踉쭁包吩걨蒙ꆌ司编ᆍ啥ꌔ턭⌁ᣀ磵砊㤙필赑掤ܾᒄ蛴눲㖅⍍杠棎᪇댃䴖憈亩㎩�ꐷ蠲ꥶᢀ퐰㘘㗽嵹띝桭ể뒊풷ኈꑶꙑꭩ汥舕咆嚣࿺ടहꋁ좴黹ᙠ檕交㎢ㄧ墺◧虏諅혒嶔贌鲙꣢観걎馤Ᏹ鏌呆쁃�Ṥ㨗䲉봢ᔠ〼씅䧘䂅袍ꙥن溍螔杪㠯∦䠣鈧⸂騒愸쾊ஐ茺边袚】卸⨇蚠艪㏥ꂪﰤ怩飩ꋤ᪮䒸蹰䣩܊椰ꊊ꣬ࣧ⇖ᦝ滃㊋�⑑혊ㅁ쌰綹Ⓠݠ⊶ί总钹ᵭĩ䵸灯똢샡Ⰼ舻㡹⺇❉⠂١㯈∻䢺⣋ꚘᏩ琚ꀁ퇘谕還뀞ꮇ⊙琇䕤鏈ㄿ೦ッ륧蔴쎓䂡Ⓨ稍海∖䉯귨묹莙᥊끴挘쑥ᰫ滃劔ꌇ嬰璽敚⠏랟⁦ܣ豊៯∵茏䢝㬎퟈슲ꆛ⨒뒍큁ނ颁鯴赅ꝗᱍ碂䞚⑷쓐�⩎娘䯙﫩䁮쑨⢲椧氜敬⍼Č蹷䊚⎎檸ګ荫咋傁檭멤�뚚秐䙊ꚣ瓾誂䓮樧䏹⠼벋�⑚䗊䢤祭☨瑶㷁늲㌠䴔訓≎ꭩ�㨫ࢳ癒笙∙⺺ቡ䵯ڰ퉙┣━⹇⾀躺⑶਩썉긴龻㦙饚爹怲닝ᷠ䛣嫡墌∱洡ᔪ角ℭߢ騝斱ṑ띝᭶뙙齏�ᨵ卯좝炩픲ᨱ驤耀඄ः蟨㴂駦琾徐ᘨ䅢舖妖鮤觮ᅵ歽襴뚥蓟懓嬥洞溕䱞呒넂ᤫ鉱湡뗧퍐挸⛮훓㽅㌩瑓☩畡俦∢笼䓓珝諣碾ҟ㾠愣鋂灶✂翏�黰揮밀䉱븐鱘ﵩﵽꦼྙﱂ褉፤忠↢ᔕ᧻㌃ӉḆ텠옐骘噎줔✠갆೰剒⁠먯ت変ꅤઢ谈嫤⑐䂙赂욽傀췌숍⽀젳賑筛䷂㔍ꖂ亁ℓ钂ف顄냬촢⌟뉡ㆎ㍈Ӊ⋓ᰓ儙謲한재쐁撬⫐鋆赾ꤕ輻佇㌽䵢줆ꗊꎞ饶燇�⠍Შ崹룞垚ꅦ癊㗬቗㷧譱죭씠ᾝ਼篋孅క砏긲暌ᄪ擰醌鼯ᅦ顅걋퉝廩ゐ锡䂅뀉遊�㽥缂䉳푆ꅠᆅ鲥隲뙟윸㜐묳䫙䆺䲇ᾕ줮딪╘ꣲથ걚鳕᡺쪆ᢅ液㖫卨ᵚ䉴Ầ浜굏牒࡫풱ꨢ湭噌��뜒햳ᚶ찕跇撯釨䢧愢끕䷧摁旎黧㙸낰嫠＄⯘ጞ祐遗㔬୓䖏ച₋薝ꞿ鏅昉ꃘ廉儍곷ꙩ㺙ཱུ쫌䐸칩ݛ룳Ჯ췂垑᛼୸⽭쿀▀芖湍✴뜏ⱹ㝄㥛ꬪꚃ⪣ؔ뀠�渤涭飓㺈ꩺ✅屭닶݋넻絮疹ꚇ盦괘벭语푀矶쨪늇氅　홱쥂ຠ₞萍옚ₘ㊀莧붃㢓직屛ྼ쾱鬉㑆貉㷴ྫ趧�瀈䬡谱撐壉즙䱏␃䣤접墋桲䝅ꌑ횦蒎鬤婬㋲㠆奸鸑∝⨐슾⎆꼬愹亀⻨鱷䰹⬼ᜍ綜隒欬⬇ꢛ뽻갦湡鲶헖鎼␝⬬㦉闃᩸沣�즮樰갞孌圦详ግᩂ걵袋㞟靘ᠩ櫙䷥斒茢♸왑鍚䡛◔棘匓ᚢ谉돣⪘삘垍齞矨卜棜醧ꎜꒉ높㟨낫ᴢ쐵權槓샋榇ወ㷇燥�궫Ầ頲酼ᄹࢄ�輧苆砀琌䇈倾腬ꗷ끲歎밃໰쇠�鋏̍騌휇ꇎፎꐫ議갟乍祘霰燦ꖀ듁ꨴ꧰�Ù铱௝뀗玪蓂뗐ﺿ䠥�彵�声띉ⴈᝠ냤鱬�첗鵄犎လ㬈㣬祘ᔠ뻌苲ṗ뾊椐솤⠞퉀敫ⵍ糛邾㝙븡✴撜튶纎톶긫㇁鋅ᕍࣙ㐝貵涑诼ꎡ䒽詑ஷ䯄้촹ɜꈤ✝낑맗⁢褻蘥쓃쏹ꊒ䫁椯༽⮷㙍ҹⴘ钷짐詂넩쾎ᕔ쀭癀躑哂ᡨ椴⬄䝛䣩ꅱ⋝ẕ葿峷㤓뱇섅日岄Ꮃ좑ア䖳ꄰ鷹䕹勋揼벳䷮Ꭳ鑸䅠㷙䰑恩ೃ숆戓鰆濾┿튓惈끀푦ց漄姾䷥鞵ꅓⱿ被㋚꫙曣ൣ둱⻄푚ﾯ诛㦿ⲝ銉ךּ䊨↔큰瘙䧎憰®䝨毂﨏घ懄惨薄ⓞᅴ狯쁝瞺탿␙ᅪষٸࡢ䑈쮺೓䄻⫢諬堯㇠⨧傫陦云灴孔辪⤼篅⛣垲┾�ﯟ芲ﷰ霵�䖪ﾇⷎ톀륑틔௝泠ٲ韙㿙闹霫⽲농深昨䟂抗넖븶୸䧅黽鮇ꦗﰗ䔛氍ꛍ驯馇篠ကᘀ䡊ꇀ‷ᓿ⿰耑랠⌱텮門켳ࡂꀅᙀ
</details>

<details>
  <summary>'map' (click me)</summary>
  {"version":1,"drawing":{"sand":[[5,14,4,14,4,10,3,10,2,9,2,7,3,6,5,6,5,7,6,7,6,8,7,9,8,9,8,10,9,10,10,11,12,11,12,10,15,10,16,11,16,13,19,13,20,12,22,12,23,11,24,12,26,12,27,11,29,11,29,10,31,10,32,11,32,10,33,9,36,9,37,10,37,12,38,12,38,11,40,11,41,12,44,12,44,11,47,11,48,12,48,13,51,10,51,7,52,6,58,6,59,7,59,9,61,9,64,12,64,13,66,13,67,12,67,11,69,9,73,9,75,11,77,11,79,13,85,13,86,12,90,12,91,11,93,11,93,10,95,10,96,11,96,13,97,12,97,11,98,10,102,10,102,11,103,10,103,9,107,9,107,17,108,18,108,21,107,22,107,24,106,25,106,28,107,29,107,36,108,37,109,37,109,38,110,39,111,39,111,41,109,41,109,43,108,44,107,44,107,49,109,51,109,53,110,53,111,54,111,57,109,59,108,59,107,58,106,59,106,65,107,66,107,68,110,71,110,73,109,74,109,77,107,79,107,82,104,85,104,88,105,89,105,93,103,95,100,95,98,93,96,93,94,95,91,95,90,94,89,95,88,95,87,96,84,96,81,93,76,93,75,92,75,91,74,90,74,81,73,80,73,79,70,76,70,74,75,69,80,69,81,68,84,68,89,63,90,63,91,62,92,62,92,59,91,58,91,46,90,45,89,45,88,44,87,44,85,42,84,42,83,41,83,39,85,37,85,32,83,30,83,29,82,28,82,27,81,26,81,25,78,22,75,22,74,21,73,21,71,19,70,19,69,18,60,18,59,17,56,17,56,20,57,21,57,22,58,23,59,23,60,22,67,22,68,23,69,23,71,25,72,25,73,26,77,26,79,28,79,30,80,31,80,32,82,34,82,36,81,37,80,37,79,36,69,36,68,37,64,37,60,41,60,44,58,46,53,41,52,41,51,40,46,40,45,41,44,41,43,42,38,42,37,43,33,43,32,42,30,42,29,41,21,41,20,40,20,39,18,37,17,37,16,38,8,38,7,37,6,37,5,36,5,31,6,30,6,27,5,26,5,25,6,24,6,22,5,21],[82.5,15.5,82,16,83,16],[67,33,68,32,59,32,60,33],[55,32,54,33,55,33,56,32],[18,23,18,24,20,26,20,27,21,26],[39,46,44,46,45,45,46,45,47,44,49,44,50,45,51,45,58,52,58,60,61,63,64,63,65,62,68,62,68,61,69,61,72,64,72,66,67,71,67,77,68,78,68,79,70,81,70,90,69,91,69,92,68,93,63,93,62,94,58,94,57,93,54,93,53,92,50,92,49,93,46,93,46,92,42,88,39,88,37,86,37,91,27,91,27,86,25,86,18,93,15,93,14,94,11,94,10,93,7,93,5,91,5,87,6,86,6,83,5,82,5,79,6,78,6,75,5,74,5,73,6,72,6,69,5,68,5,63,4,62,4,59,3,59,2,58,2,57,3,56,4,56,4,54,3,53,3,51,4,50,5,50,5,44,7,42,8,43,9,43,9,42,17,42,20,45,28,45,29,46,31,46,32,47,38,47],[31,22,32,23,33,23,35,21,35,18,34,17,33,17,31,19],[68,58,67,59,62,59,61,58,61,57,60,56,60,50,63,47,63,43,65,41,70,41,71,40,79,40,80,41,80,43,83,46,84,46,85,47,86,47,87,48,87,59,83,63,81,63,80,64,76,64,70,58]],"level1":[[67,33,68,32,59,32,60,33],[55,32,54,33,55,33,56,32],[69,36,68,37,64,37,60,41,60,44,58,46,53,41,52,41,51,40,46,40,45,41,44,41,43,42,38,42,37,43,33,43,32,42,30,42,29,41,21,41,20,40,20,39,18,37,17,37,16,38,12,38,12,36,13,35,13,30,12,29,12,26,13,25,13,23,12,22,12,18,13,17,13,16,14,15,14,14,15,13,98,13,100,15,100,18,101,19,101,23,100,24,100,26,101,27,101,30,100,31,100,33,101,34,101,36,100,37,100,39,102,41,102,43,100,45,100,50,103,53,110,53,111,54,111,57,109,59,108,59,107,58,106,58,105,57,103,57,102,58,102,60,100,62,100,65,102,67,102,70,101,71,101,73,100,74,100,75,99,76,99,82,98,83,95,83,94,84,91,84,89,86,84,86,81,83,76,83,75,84,74,84,74,81,73,80,73,79,70,76,70,74,75,69,80,69,81,68,84,68,89,63,90,63,91,62,92,62,92,59,91,58,91,46,90,45,89,45,88,44,87,44,85,42,84,42,83,41,83,39,85,37,85,32,83,30,83,29,82,28,82,27,81,26,81,25,78,22,75,22,74,21,73,21,71,19,70,19,69,18,60,18,59,17,56,17,56,20,57,21,57,22,58,23,59,23,60,22,67,22,68,23,69,23,71,25,72,25,73,26,77,26,79,28,79,30,80,31,80,32,82,34,82,36,81,37,80,37,79,36],[82.5,15.5,82,16,83,16],[39,46,44,46,45,45,46,45,47,44,49,44,50,45,51,45,58,52,58,60,61,63,64,63,65,62,68,62,68,61,69,61,72,64,72,66,67,71,67,77,68,78,68,79,70,81,70,84,69,84,68,83,62,83,61,84,60,84,59,83,57,83,56,84,52,84,51,83,14,83,13,82,13,78,12,77,12,74,13,73,13,71,12,70,12,66,13,65,13,63,11,61,11,60,10,59,10,56,11,55,12,55,12,51,13,50,13,44,12,43,12,42,17,42,20,45,28,45,29,46,31,46,32,47,38,47],[31,22,32,23,33,23,35,21,35,18,34,17,33,17,31,19],[68,58,67,59,62,59,61,58,61,57,60,56,60,50,63,47,63,43,65,41,70,41,71,40,79,40,80,41,80,43,83,46,84,46,85,47,86,47,87,48,87,59,83,63,81,63,80,64,76,64,70,58]],"rock":[[5,6,5,7,6,7,6,8,7,9,8,9,8,10,9,10,10,11,12,11,12,10,15,10,16,11,16,13,15,13,14,14,14,15,13,15,12,16,9,16,8,15,6,15,5,14,4,14,4,10,3,10,2,9,2,7,3,6],[9,38,8,38,7,37,9,37],[10,44,7,44,6,43,7,42,8,43,9,43,9,42,10,43],[22,12,23,11,24,12,26,12,27,11,29,11,29,10,31,10,32,11,32,10,33,9,36,9,37,10,37,12,38,12,38,11,40,11,41,12,44,12,44,11,47,11,48,12,48,13,19,13,20,12],[48,13,52,9,53,10,53,11,58,11,58,9,61,9,64,12,64,13,50,13,50,14,49,14],[67,12,67,11,69,9,73,9,75,11,77,11,79,13,66,13],[59,13,59,14,58.5,13.5],[3,53,3,51,4,50,7,50,9,52,9,54,8,55,8,59,6,61,4,61,4,59,3,59,2,58,2,57,3,56,4,56,4,54],[69,91,69,90,70,89,70,90],[75,89,75,91,74,90,74,89],[106,36,107,37,109,37,109,38,110,39,111,39,111,41,109,41,109,43,108,44,107,44,106,43,106,41,104,41,102,39,102,37,103,36],[96.5,11.5,98,10,102,10,102,11,103,10,103,9,107,9,107,12,105,14,103,14,101,16,98,13,96,13,97,12],[85,13,86,12,90,12,91,11,93,11,93,10,95,10,96,11,96,13],[37,85,35,85,36,86,37,86,37,91,27,91,27,86,26,85,25,85,25,83,27,83,27,86,31,86,31,85,30,85,29,84,29,83,37,83]],"level2":[[16,15,16,14,17,13,97,13,100,16,100,29,99,30,99,33,100,34,100,37,99,38,99,40,100,41,100,47,99,48,98,48,97,49,97,50,92,55,91,55,91,46,90,45,89,45,88,44,87,44,85,42,84,42,83,41,83,39,85,37,85,32,83,30,83,29,82,28,82,27,81,26,81,25,78,22,75,22,74,21,73,21,71,19,70,19,69,18,60,18,59,17,56,17,56,20,57,21,57,22,58,23,59,23,60,22,67,22,68,23,69,23,71,25,72,25,73,26,77,26,79,28,79,30,80,31,80,32,82,34,82,36,81,37,80,37,79,36,77,36,77,33,76,32,68,32,67,33,60,33,59,34,56,34,55,33,53,33,49,29,42,29,40,31,32,31,30,33,23,33,22,32,21,32,20,31,19,31,17,29,17,26,16,25,16,19,17,18,17,16],[82.5,15.5,82,16,83,16],[31,22,32,23,33,23,35,21,35,18,34,17,33,17,31,19],[79,40,80,41,80,43,83,46,84,46,85,47,86,47,87,48,87,55,85,55,82,52,81,52,80,51,79,51,78,50,77,50,76,49,76,44,77,43,77,40]],"level3":[[22,14,38,14,39,15,39,16,42,19,42,21,40,23,38,23,36,25,30,25,28,23,24,23,22,21,21,21,20,20,20,16],[31,22,32,23,33,23,35,21,35,18,34,17,33,17,31,19],[51,14,61,14,63,16,63,18,60,18,59,17,56,17,56,20,57,21,57,22,58,23,59,23,60,22,63,22,61,24,61,25,59,27,54,27,53,26,52,26,49,23,49,17,50,16,50,15],[98,28,97,28,95,30,91,30,90,29,90,28,86,24,84,24,83,23,83,21,82,20,81,20,80,19,79,19,78,18,78,16,80,14,95,14,98,17]],"pathBrick":[],"pathDirt":[103,89,111,89,111,91,103,91]}}
</details>

**Comment by eugeneration** [comment]
Thanks for the extensive troubleshooting details! It helped me find out where the issue was (probably) stemming from

In #58 I changed the compression to do UTF 16 rather than the default which compresses to an invalid js string. Because it is a valid string, steganography should be able to correctly store the data.
