### ISSUE TITLE
Double South Outlet Map

### ISSUE THREAD

**Issue by Conpoy** [eugeneration/HappyIslandDesigner#72]
Thanks for this tool! Just made a map for one of the Double South Outlet:

[`{"version":1,"objects":{"amenities_dock":[105,84],"amenities_airport":[60,84]},"drawing":{"sand":[[31,21,32,22,33,22,39,28,40,28,41,29,47,29,47,28,49,28,50,27,56,27,56,28,57,28,57,37,56,37,56,38,55,39,53,39,52,40,52,41,51,41,51,42,49,44,49,45,48,46,48,47,44,47,43,48,38,48,36,50,33,50,29,54,28,54,27,55,27,57,26,58,26,62,23,65,23,66,21,68,21,69,20,70,20,73,21,74,21,78,22,78,22,80,23,81,23,84,22,84,22,86,21,86,21,88,20,88,20,92,19,92,19,93,14,93,14,92,13,92,13,91,12,91,12,90,11,90,11,87,10,87,10,86,9,86,9,85,8,85,8,84,7,84,6,83,6,76,7,76,7,75,8,74,8,73,6,73,5,72,4,72,2,70,2,69,3,68,6,68,6,66,5,66,5,63,6,63,6,58,5,58,5,56,6,56,6,52,5,52,5,47,4,47,4,46,3,45,2,45,2,39,3,39,3,38,4,37,4,33,5,33,5,29,6,29,6,28,5,28,5,27,6,26,6,25,7,25,7,24,6,24,6,23,5,23,4,22,3,22,3,18,4,18,4,17,6,17,5,16,5,15,6,15,5,14,4,14,3,13,3,12,4,11,1,8,1,7,3,5,4,5,7,8,7,9,8,9,9,10,10,10,11,11,13,9,14,10,15,10,16,11,16,9,18,9,19,8,21,10,21,12,22,11,24,11,25,12,26,12,27,11,31,11,32,12,34,12,34,11,37,11,38,10,39,10,40,11,40,10,41,10,42,11,46,11,47,12,48,12,48,10,50,8,50,7,59,7,59,8,60,8,64,12,66,12,66,11,67,11,67,9,73,9,73,10,75,10,76,11,76,10,77,10,77,11,78,11,78,12,77,13,78,13,78,12,82,12,83,11,84,11,85,12,86,12,87,11,88,11,89,12,89,13,91,11,94,11,95,12,97,12,97,11,96,11,98,9,100,9,101,10,102,10,102,9,103,8,106,8,107,9,107,10,106,10,107,11,107,18,106,18,106,20,107,20,107,23,106,24,106,27,107,27,107,33,108,34,108,38,107,38,107,41,106,41,106,45,107,45,107,51,105,51,105,56,106,56,106,60,107,60,107,62,108,62,108,65,107,65,107,67,106,67,106,68,105,68,105,70,104,70,104,74,105,74,105,76,106,76,106,77,107,78,107,82,108,82,108,85,107,86,107,88,105,88,105,89,102,89,102,90,100,90,100,91,99,91,99,92,97,92,97,93,95,93,94,92,93,92,93,91,92,90,92,87,91,87,91,86,90,86,90,84,91,84,90,83,90,80,93,77,93,70,91,68,91,67,92,66,92,65,91,64,90,64,88,62,88,60,90,58,90,54,87,51,87,49,82,44,81,44,79,42,75,42,74,41,65,41,61,37,61,28,60,27,60,26,59,26,58,25,57,25,56,24,56,23,49,23,46,26,41,26,40,25,40,24,35,19,34,19,33,18,31,18,31,17,27,17,26,16,25,16,24,17,24,20,26,22,27,22,27,21],[75,20,77,18,77,16,71,16,71,18,73,20],[6.5,13.5,7,13,6,13],[57,86,57,87,56,87,56,88,55,88,53,90,52,90,52,91,51,91,51,92,49,92,49,93,47,93,47,94,44,94,43,93,40,93,40,94,39,94,38,95,37,95,36,94,34,94,33,93,28,93,28,92,27,92,27,88,26,87,26,81,25,80,25,79,24,78,24,70,26,68,26,67,28,65,29,65,29,64,30,63,30,58,31,57,32,57,35,54,36,54,38,52,43,52,44,51,45,51,46,50,49,50,52,47,52,46,55,43,56,43,58,41,60,41,63,44,63,46,64,47,64,51,65,52,65,53,70,58,71,58,72,59,77,59,80,62,82,62,83,63,84,63,87,66,87,69,89,71,89,76,88,77,87,77,87,79,86,80,87,80,87,83,86,84,86,91,85,91,85,93,81,93,80,92,78,92,77,91,76,91,76,90,74,88,70,88,70,87,69,87,69,89,70,90,70,91,69,91,69,92,59,92,59,91,58,90,58,86],[87,40,90,37,90,35,89,34,87,34,84,37,84,39,85,40],[72,55,67,50,67,45,68,44,73,44,74,45,77,45,79,47,80,47,80,48,81,48,84,51,84,52,86,54,86,58,85,59,83,59,82,58,81,58,78,55]],"level1":[[98,83,93,83,92,84,91,84,90,83,90,80,93,77,93,70,91,68,91,67,92,66,92,65,91,64,90,64,88,62,88,60,90,58,90,54,87,51,87,49,82,44,81,44,79,42,75,42,74,41,65,41,61,37,61,28,60,27,60,26,59,26,58,25,57,25,56,24,56,23,49,23,46,26,41,26,40,25,40,24,35,19,34,19,33,18,31,18,31,17,27,17,26,16,25,16,24,17,24,20,26,22,27,22,27,21,31,21,32,22,33,22,39,28,40,28,41,29,47,29,47,28,49,28,50,27,56,27,56,28,57,28,57,37,56,37,56,38,55,39,53,39,52,40,52,41,51,41,51,42,49,44,49,45,48,46,48,47,44,47,43,48,38,48,36,50,33,50,29,54,28,54,27,55,27,57,26,58,26,62,23,65,23,66,21,68,21,69,20,70,20,73,21,74,21,78,22,78,22,80,23,81,23,84,18,84,18,83,17,83,16,84,14,84,14,82,13,81,13,79,12,78,12,76,11,75,11,74,9,72,8,73,6,73,5,72,4,72,2,70,2,69,3,68,7,68,7,67,9,67,10,66,12,66,13,65,13,62,12,61,12,58,13,57,13,55,12,54,12,50,13,49,13,47,12,46,12,45,10,43,10,41,11,40,11,37,12,36,12,35,13,34,13,30,12,29,12,24,11,23,11,20,13,18,13,15,14,15,15,14,15,13,64,13,64,12,67,12,67,13,77,13,78,12,82,12,82,13,89,13,90,12,91,13,95,13,95,12,97,12,97,13,98,13,100,15,99,16,99,17,100,18,100,21,99,22,99,25,100,26,100,30,99,31,99,34,100,35,100,40,99,41,99,42,100,43,100,46,99,47,99,48,100,49,100,54,99,54,99,68,100,69,100,72,101,73,101,75,100,76,100,78,99,79,99,82,98,82],[75,20,77,18,77,16,71,16,71,18,73,20],[87,40,90,37,90,35,89,34,87,34,84,37,84,39,85,40],[72,55,67,50,67,45,68,44,73,44,74,45,77,45,79,47,80,47,80,48,81,48,84,51,84,52,86,54,86,58,85,59,83,59,82,58,81,58,78,55],[31,57,32,57,35,54,36,54,38,52,43,52,44,51,45,51,46,50,49,50,52,47,52,46,55,43,56,43,58,41,60,41,63,44,63,46,64,47,64,51,65,52,65,53,70,58,71,58,72,59,77,59,80,62,82,62,83,63,84,63,87,66,87,69,89,71,89,76,88,77,87,77,87,79,86,80,87,80,87,83,86,84,84,84,84,83,47,83,46,84,43,84,42,85,37,85,36,84,35,84,34,83,29,83,28,84,26,84,26,81,25,80,25,79,24,78,24,70,26,68,26,67,28,65,29,65,29,64,30,63,30,58]],"level2":[[46,36,45,37,37,37,37,39,35,39,34,40,33,40,33,41,31,43,30,43,30,44,27,44,26,45,26,46,24,48,24,52,23,52,23,54,20,57,19,57,19,56,16,56,16,57,15,57,15,56,14,56,14,54,13,53,13,51,14,50,14,48,15,48,15,46,14,45,15,44,15,40,14,40,14,31,13,30,13,24,14,23,14,21,13,21,13,15,14,15,15,14,15,13,64,13,64,12,67,12,67,13,77,13,78,12,82,12,82,13,89,13,91,15,91,22,90,23,90,27,89,28,89,29,88,29,87,30,81,30,80,31,78,31,77,32,75,32,74,31,70,31,69,32,61,32,61,28,60,27,60,26,59,26,58,25,57,25,56,24,56,23,49,23,46,26,41,26,40,25,40,24,35,19,34,19,33,18,31,18,31,17,27,17,26,16,25,16,24,17,24,20,26,22,27,22,27,21,31,21,32,22,33,22,39,28,40,28,41,29,47,29,47,28,49,28,50,27,56,27,56,28,57,28,57,32,51,32,49,34,49,35,48,36],[75,20,77,18,77,16,71,16,71,18,73,20]],"rock":[[9,20,9,22,8,22,8,23,5,23,4,22,3,22,3,18,4,18,4,17,7,17,7,19,8,19,8,20],[7,8,7,9,8,9,9,10,10,10,11,11,13,9,14,10,15,10,16,11,16,9,18,9,19,8,21,10,21,12,22,11,24,11,25,12,26,12,27,11,31,11,32,12,34,12,34,11,37,11,38,10,39,10,40,11,40,10,41,10,42,11,46,11,47,12,48,12,48,10,50,8,50,7,51,7,51,8,52,8,53,9,53,10,52,10,52,11,58,11,58,9,59,9,59,8,60,8,64,12,64,13,15,13,15,14,14,15,13,15,12,16,9,16,8,15,6,15,5,14,4,14,3,13,3,12,4,11,1,8,1,7,3,5,4,5],[20,89,20,92,19,92,18,91,18,90,19,90,19,89],[21,87,21,88,20,88,20,87],[28,89,28,91,27,91,27,89],[57,83,59,83,59,86,61,86,61,85,62,85,62,84,61,84,61,83,69,83,69,86,67,86,68,87,69,87,69,89,70,90,70,91,69,91,69,92,59,92,59,91,58,90,58,85,57,84],[86,90,86,91,85,91,85,92,84,92,84,90],[9,25,9,26,10,26,10,29,6,29,6,28,5,28,5,27,6,26,6,25],[93,90,92,90,92,88,93,88],[106,18,106,20,107,20,107,23,106,24,106,26,104,26,104,25,103,25,102,24,102,21,103,20,104,20,104,19,105,19,105,18],[101,51,103,51,103,54,101,56,100,56,100,52,101,52],[98,13,97,13,97,11,96,11,98,9,100,9,101,10,102,10,102,9,103,8,106,8,107,9,107,10,106,10,107,11,106,11,106,12,104,14,102,14,101,15,100,15],[66,11,67,11,67,9,73,9,73,10,75,10,76,11,76,10,77,10,77,11,78,11,78,12,77,13,67,13,67,12,66,12],[82,13,82,12,83,11,84,11,85,12,86,12,87,11,88,11,89,12,89,13],[91,11,94,11,95,12,95,13,91,13,90,12]],"pathDirt":[53,72,52,71,52,63,53,62,63,62,64,63,64,71,63,72],"level3":[[26,27,25,28,25,30,24,31,22,31,22,32,21,32,21,33,20,34,20,35,19,35,18,36,16,36,16,35,15,35,15,30,14,29,14,25,15,25,15,24,16,23,16,21,14,19,14,16,15,16,16,15,16,14,27,14,29,16,29,17,27,17,26,16,25,16,24,17,24,20,26,22,27,22,27,21,29,21,29,24,28,24,28,25,27,25,26,26],[54,18,53,17,53,16,55,14,79,14,80,15,80,19,78,21,74,21,73,22,68,22,67,21,66,21,65,20,60,20,59,19,56,19,55,18],[75,20,77,18,77,16,71,16,71,18,73,20]],"pathBrick":[]}}`]
![ISLAND ](https://user-images.githubusercontent.com/63691699/79293661-25eb0500-7e89-11ea-8af5-285daa06af9d.png)

**Comment by eugeneration** [comment]
Merging into #59
