### ISSUE TITLE
Formatting map files

### ISSUE THREAD

**Issue by Goten87** [eugeneration/HappyIslandDesigner#76]
what do i need to load in when i want to open/load a map
i have a A2 Template.js file now on my desktop but i cant seem to open it with Load Map

is there something i need to do

i took over the Template.js in the folder data and changed all the extra data after the = to my own data

also a save map will be nice to have so we can save the map local on our pc

**Comment by lilasquared** [comment]
on the site you can click the hamburger menu icon and you can save the map from there.  It saves an image of the map and encodes the data into the image so you can load it later
