### ISSUE TITLE
Can't move the corners in the photo uploader

### ISSUE THREAD

**Issue by FayezButts** [eugeneration/HappyIslandDesigner#96]

**Comment by FayezButts** [comment]
A couple of weeks ago I was able to upload a photo and move the little yellow circles to align the grid but now they don't seem to be movable. This would be ok but they also seem to show up about 8-16 px left of my pointer when I click, making it hard to get it right on the first try.
![image](https://user-images.githubusercontent.com/32073174/82136125-4257c580-97d8-11ea-8097-87a311575a82.png)

**Comment by eugeneration** [comment]
Ah you are totally right I didn't realize I broke this! Let me know if it works now??

**Comment by FayezButts** [comment]
Yep, looks like it's working perfectly! Thank you!
